/**
 * 工具名 → 中文动作短语：任务进度卡的主文案。
 * 未收录的工具回退显示原始工具名。桌面端（ChatShared）与移动端（App）共用这一份，防漂移。
 */
export const TOOL_ACTION_LABEL: Record<string, string> = {
  // opencode 内置
  bash: '执行命令',
  read: '读取文件',
  write: '写入文件',
  edit: '编辑文件',
  patch: '应用补丁',
  grep: '搜索文本',
  glob: '匹配文件',
  list: '浏览目录',
  todowrite: '更新待办',
  todoread: '读取待办',
  webfetch: '抓取网页',
  task: '派发子任务',
  // Jeff 管理工具
  jeff_agent_create: '创建智能体',
  jeff_agent_update: '更新智能体',
  jeff_agent_delete: '删除智能体',
  jeff_agent_list: '查看智能体',
  jeff_agent_get: '查看智能体',
  jeff_project_create: '创建项目群',
  jeff_project_update: '更新项目群',
  jeff_project_delete: '解散项目群',
  jeff_project_list: '查看项目群',
  jeff_project_add_member: '添加群成员',
  jeff_project_remove_member: '移除群成员',
  jeff_task_create: '创建任务',
  jeff_task_update: '更新任务',
  jeff_task_delete: '删除任务',
  jeff_task_list: '查看任务',
  jeff_cron_create: '创建定时任务',
  jeff_cron_update: '更新定时任务',
  jeff_cron_delete: '删除定时任务',
  jeff_cron_list: '查看定时任务',
  jeff_memory: '整理记忆',
  jeff_session_search: '搜索会话',
  jeff_delegate: '委派智能体',
  jeff_spawn_subtask: '派发子任务',
  jeff_self_update: '修正身份指令',
  // 插件
  jeff_plugin_create: '创建插件',
  jeff_plugin_update: '更新插件',
  jeff_plugin_delete: '删除插件',
  jeff_plugin_enable: '启用插件',
  jeff_plugin_list: '查看插件',
  jeff_plugin_read: '读取插件',
  // 内置浏览器
  jeff_browser_navigate: '打开网页',
  jeff_browser_click: '点击页面',
  jeff_browser_type: '填写表单',
  jeff_browser_upload: '上传文件',
  jeff_browser_screenshot: '页面截图',
  jeff_browser_set_viewport: '设置分辨率',
  jeff_browser_get_console: '读取报错',
  jeff_browser_get_content: '读取网页',
}
